### ISSUE TITLE
Create pool with cache export & import property get fail

### ISSUE THREAD

**Issue by sachin11** [zfs-linux/zfs#48]
Steps :-
1) Create zpool with cache
[root@kqinfo kqinfo]# zpool create -f tank /disk.4236/a /disk.4236/b /disk.4236/c cache /dev/sda1
[root@kqinfo kqinfo]# zpool list
NAME   SIZE   USED  AVAIL    CAP  HEALTH  ALTROOT
tank   178M   236K   178M     0%  ONLINE  -
[root@kqinfo kqinfo]# zpool status
  pool: tank
 state: ONLINE
 scrub: none requested
config:

```
    NAME            STATE     READ WRITE CKSUM
    tank            ONLINE       0     0     0
      /disk.4236/a  ONLINE       0     0     0
      /disk.4236/b  ONLINE       0     0     0
      /disk.4236/c  ONLINE       0     0     0
    cache
      sda1          ONLINE       0     0     0
```

errors: No known data errors
2) export created zpool
[root@kqinfo kqinfo]# zpool export tank
[root@kqinfo kqinfo]# zpool list
no pools available
[root@kqinfo kqinfo]# zpool status
no pools available
3) import created zpool
[root@kqinfo kqinfo]# zpool import tank
cannot import 'tank': no such pool available
[root@kqinfo kqinfo]#

**Comment by shrirang** [comment]
This is not a problem. The problem is with the import command used here. By default when we import the pool it is searched in /dev/. But if we want to import the pool whose disks ( files) are on other path than /dev. then we need to specify its parent directory to import that pool.
Ex.
$] zpool create tank /home/kqinfo/dev1 /home/kqinfo/dev2  cache sda

$]zpool status
  pool: tank
 state: ONLINE
 scan: none requested
config:

```
NAME                 STATE     READ WRITE CKSUM
tank                 ONLINE       0     0     0
  /home/kqinfo/dev1  ONLINE       0     0     0
  /home/kqinfo/dev2  ONLINE       0     0     0
cache
  sda1               ONLINE       0     0     0
```

errors: No known data errors

$] zpool export tank

$] zpool status
    no pools available

$] zpool import tank
cannot import 'tank': no such pool available

But if we do like below

$] zpool import -d /home/kqinfo/ tank

$] zpool status
  pool: tank
 state: ONLINE
 scan: none requested
config:

```
NAME                 STATE     READ WRITE CKSUM
tank                 ONLINE       0     0     0
  /home/kqinfo/dev1  ONLINE       0     0     0
  /home/kqinfo/dev2  ONLINE       0     0     0
cache
  sda1               ONLINE       0     0     0
```

errors: No known data errors
