### ISSUE TITLE
cp -r hangs machine

### ISSUE THREAD

**Issue by mitra** [zfs-linux/zfs#49]
-----Original Message-----
From: Don McGregor [mailto:mcgredo@nps.edu]
Sent: Monday, November 08, 2010 11:57 AM
To: Darshin Vyas - KQ Infotech
Subject: ZFS

I'm not sure if this is a ZFS problem, or, more likely, a RHEL 6 beta 2
problem, but:

Copying 10 GB of space, and 1.75 million individual files. From a raidz
volume
to another directory on that same volume. cp -R oldDir newDir

kswapd goes nuts and takes up 100% of CPU. One of the ZFS threads is also
taking up a lot of CPU. I can't tell exactly which one; the terminal running
top is obscured and I can't open a new one. Percent memory in use is
low (24GB host memory)

Total number of files on the raidz volume is in the 5 million range.

Unfortunately the host is locked up and I can't get better diagnostics.

**Comment by mitra** [comment]
Sandip try and reproduce this problem.

**Comment by rohan-puri** [comment]
even i had problems with the cp -r 

figured out this issue.
the problem is in the linux kernel the issue is that some where in kernel that ima related function allocates memoy using GFP_KERNEL flag and when the reclaiming is done then this fs related memory is being freed and lock on those inodes already have been held and again tries the same leading to deadlock.

the GFP_NOFS flag is made use of now which is the fix and appears in 2.6.33 (checked) need to check for 2.6.32

0xffff8800058a7070 0xffffffff814f3609 mutex_lock+0x43 (0xffff880011507848)
0xffff8800058a70b0 0xffffffffa03624b0 [zfs]zfs_zinactive+0x9f (0xffff880019085b58)
0xffff8800058a7110 0xffffffffa0358d53 [zfs]zfs_inactive+0x24f (invalid)
0xffff8800058a7180 0xffffffffa03f2478 [lzfs]lzfs_clear_vnode+0xe5 (0xffff88001909cb98)
0xffff8800058a71c0 0xffffffff8113d117 clear_inode+0xab (0xffff88001909cb98)
0xffff8800058a71f0 0xffffffff8113d1e3 dispose_list+0x5c (0xffff8800058a7238)
0xffff8800058a7230 0xffffffff8113d49d shrink_icache_memory+0x1f9 (invalid)
0xffff8800058a7290 0xffffffff810f03e7 shrink_slab+0xef (invalid, invalid, invalid)
0xffff8800058a7300 0xffffffff810f1a7e do_try_to_free_pages+0x26b (invalid, 0xffff8800058a7398)
0xffff8800058a7390 0xffffffff810f1cf7 try_to_free_pages+0x7b (invalid, invalid, invalid, 0x0)
0xffff8800058a73f0 0xffffffff810ea3c6 __alloc_pages_nodemask+0x3c4 (invalid, invalid, 0xffff88000000c800, 0x0)
0xffff8800058a74e0 0xffffffff81114aab alloc_pages_current+0xa8 (invalid, invalid)
0xffff8800058a7520 0xffffffff8111b532 alloc_slab_page+0x2e (invalid, invalid, invalid)
0xffff8800058a7540 0xffffffff8111b604 new_slab+0x7e (0xffff88001e28a000, invalid, invalid)
0xffff8800058a7590 0xffffffff8111c201 __slab_alloc+0x1f1 (0xffff88001e28a000, invalid, invalid, 0xffffffff81228a5f, invalid)
0xffff8800058a7600 0xffffffff8111ca61 kmem_cache_alloc+0xa8 (0xffff88001e28a000, invalid)

0xffff8800058a7660 0xffffffff81228a5f ima_iint_insert+0x40 (0xffff880006d3dd98)
0xffff8800058a76a0 0xffffffff81228b2b ima_inode_alloc+0x2a
0xffff8800058a76c0 0xffffffff8113cdc6 inode_init_always+0xf1 (0xffff88000cd58000, 0xffff880006d3dd98)
0xffff8800058a76f0 0xffffffff8113cf34 alloc_inode+0x56 (0xffff88000cd58000)
0xffff8800058a7720 0xffffffff8113dee9 iget_locked+0x5d (0xffff88000cd58000, 0x246a)
0xffff8800058a7770 0xffffffffa0362187 [zfs]zfs_mknode+0xc1c (0xffff88001b1a6ce0, 0xffff880009635000, 0xffff8800051dec00, 0xffff88000cca4900, 0x51dec0000000000, 0xffff8800058a7ca0, 0xffff8800058a7c68)
0xffff8800058a7be0 0xffffffffa035d366 [zfs]zfs_create+0x42f (invalid, 0xffff880009c63160, 0xffff880009635000, invalid, 0x51d9800000081a4, 0xffff8800058a7d28, 0xffff88000cca4900, 0x0, 0x0)
0xffff8800058a7cf0 0xffffffffa03f3bad [lzfs]lzfs_vnop_create+0x1ad (0xffff880006d3ec98, 0xffff880009c630c0, invalid)
0xffff8800058a7d70 0xffffffff81131ff4 vfs_create+0x87 (0xffff880006d3ec98, 0xffff880009c630c0, invalid, 0xffff8800058a7e28)
0xffff8800058a7dc0 0xffffffff81134f34 do_filp_open+0x324 (invalid, 0xffff8800114ce000, invalid, invalid, invalid)
0xffff8800058a7f00 0xffffffff81125434 do_sys_open+0x71 (invalid, invalid, invalid, invalid)
0xffff8800058a7f60 0xffffffff81125561 sys_open+0x33 (invalid, invalid, invalid)
bb_parse_opcode: no match at [kernel]system_call 0xffffffff81011fa7 - 'cs'
0xffff8800058a7f80 0xffffffff81012032 system_call_fastpath+0x16 (invalid, invalid, invalid, invalid, invalid, invalid, 0x33, 0x10246, 0x7fffeac7ebc8)
[0]kdb>
